/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 * @author User
 */
public class PaymentFormNew extends javax.swing.JInternalFrame {

    /**
     * Creates new form paymentForm
     */
    public PaymentFormNew() {
        initComponents();
    }
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        areaCbx = new javax.swing.JComboBox<>();
        priceLandTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tSilverRadioButton = new javax.swing.JRadioButton();
        tGoldRadioButton = new javax.swing.JRadioButton();
        tDiamondRadioButton = new javax.swing.JRadioButton();
        LargeLandTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buildingPriceTxt = new javax.swing.JTextField();
        availableLandTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        installmentAmountTxt = new javax.swing.JTextField();
        PPNTxt = new javax.swing.JTextField();
        installmentMonthTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        agreementCbx = new javax.swing.JCheckBox();
        prosesButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FORM PENJUALAN APARTMENT VILLA GADING");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Apartment");

        jLabel3.setText("Area");

        areaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*** PILIH ***", "Bougenvile", "Melati", "Flamboyan" }));
        areaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCbxActionPerformed(evt);
            }
        });

        priceLandTxt.setEditable(false);
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        priceLandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceLandTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Bangunan");

        jLabel6.setText("Tipe Apartment");

        radioButton.add(tSilverRadioButton);
        tSilverRadioButton.setText("Tipe - Silver");
        tSilverRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSilverRadioButtonActionPerformed(evt);
            }
        });

        radioButton.add(tGoldRadioButton);
        tGoldRadioButton.setText("Tipe - Gold");
        tGoldRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGoldRadioButtonActionPerformed(evt);
            }
        });

        radioButton.add(tDiamondRadioButton);
        tDiamondRadioButton.setText("Tipe - Diamond");
        tDiamondRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDiamondRadioButtonActionPerformed(evt);
            }
        });

        LargeLandTxt.setEditable(false);
        LargeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Luas Tanah Asli");

        buildingPriceTxt.setEditable(false);
        buildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        availableLandTxt.setEditable(false);
        availableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Luas Tanah Tersedia");

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPN (10%)");

        jLabel13.setText("Cicilan / Bulan");

        totalPriceTxt.setEditable(false);
        totalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPTxtActionPerformed(evt);
            }
        });

        installmentAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        PPNTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PPNTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPNTxtActionPerformed(evt);
            }
        });

        installmentMonthTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        installmentMonthTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installmentMonthTxtActionPerformed(evt);
            }
        });

        jLabel14.setText("Bulan");

        agreementCbx.setText("Setuju");
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });

        prosesButton.setText("PROSES");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        saveButton.setText("SIMPAN");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("CLEAR");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiPenjualan/Apartment Villa Gading.jpeg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(areaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orderNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(priceLandTxt))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)))
                                    .addComponent(tDiamondRadioButton))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalPriceTxt)
                                    .addComponent(DPTxt)
                                    .addComponent(installmentAmountTxt)
                                    .addComponent(PPNTxt)
                                    .addComponent(installmentMonthTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tSilverRadioButton)
                                        .addComponent(tGoldRadioButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LargeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agreementCbx)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tSilverRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tGoldRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tDiamondRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(areaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LargeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(installmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PPNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(installmentMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(agreementCbx)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesButton)
                    .addComponent(saveButton)
                    .addComponent(deleteButton))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tGoldRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGoldRadioButtonActionPerformed
        if(areaCbx.getSelectedIndex() == 0){
           JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
           radioButton.clearSelection();
       }else{
           LargeLandTxt.setText("120");
           availableLandTxt.setText("75");
           long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                   totalPrice;
           totalPrice = (availableLand * landPrice + buildingPrice);
           totalPriceTxt.setText("" + totalPrice);
           
           installmentAmountTxt.setText("");
           DPTxt.setText("");
           PPNTxt.setText("");
           installmentMonthTxt.setText("");
       }
    }//GEN-LAST:event_tGoldRadioButtonActionPerformed

    private void areaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCbxActionPerformed
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        switch(areaCbx.getSelectedIndex()){
            case 0:
                priceLandTxt.setText("");
                buildingPriceTxt.setText("");
                radioButton.clearSelection();
                LargeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                PPNTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 1:
                priceLandTxt.setText("500000");
                buildingPriceTxt.setText("90000000");
                radioButton.clearSelection();
                LargeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                PPNTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 2:
                priceLandTxt.setText("600000");
                buildingPriceTxt.setText("120000000");
                radioButton.clearSelection();
                LargeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                PPNTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            default:
                priceLandTxt.setText("700000");
                buildingPriceTxt.setText("150000000");
                radioButton.clearSelection();
                LargeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                PPNTxt.setText("");
                agreementCbx.setSelected(false);
                break;
        }
        
    }//GEN-LAST:event_areaCbxActionPerformed

    private void tSilverRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSilverRadioButtonActionPerformed
       if(areaCbx.getSelectedIndex() == 0){
           JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
           radioButton.clearSelection();
       }else{
           LargeLandTxt.setText("90");
           availableLandTxt.setText("54");
           long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                   totalPrice;
           totalPrice = (availableLand * landPrice + buildingPrice);
           totalPriceTxt.setText("" + totalPrice);
           
           installmentAmountTxt.setText("");
           DPTxt.setText("");
           PPNTxt.setText("");
           installmentMonthTxt.setText("");
       }
    }//GEN-LAST:event_tSilverRadioButtonActionPerformed

    private void tDiamondRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDiamondRadioButtonActionPerformed
        if(areaCbx.getSelectedIndex() == 0){
           JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
           radioButton.clearSelection();
       }else{
           LargeLandTxt.setText("140");
           availableLandTxt.setText("86");
           long landPrice = Long.parseLong(priceLandTxt.getText()),
                   buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                   availableLand = Long.parseLong(availableLandTxt.getText()),
                   totalPrice;
           totalPrice = (availableLand * landPrice) + buildingPrice;
           totalPriceTxt.setText("" + totalPrice);
           
           installmentAmountTxt.setText("");
           DPTxt.setText("");
           PPNTxt.setText("");
           installmentMonthTxt.setText("");
       }
    }//GEN-LAST:event_tDiamondRadioButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        orderNameTxt.setText("");
        priceLandTxt.setText("");
        buildingPriceTxt.setText("");
        LargeLandTxt.setText("");
        availableLandTxt.setText("");
        totalPriceTxt.setText("");
        DPTxt.setText("");
        installmentAmountTxt.setText("");
        installmentMonthTxt.setText("");
        PPNTxt.setText("");
        areaCbx.setSelectedIndex(0);
        radioButton.clearSelection();
        agreementCbx.setSelected(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        long  dp2 = Long.parseLong(DPTxt.getText());
        if(totalPriceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilihan belum lengkap");
        }else if(DPTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP harus diisi terlebih dahulu");
        }else if(dp2 <= 20000000) {
            JOptionPane.showMessageDialog(null, "DP Minimal harus Rp. 20.000.000,00");
        }else if(installmentAmountTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi jumlah cicilan yang diinginkan");
        }else if(agreementCbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Tombol Telah Ditekan");
            agreementCbx.setSelected(true);
        }else{
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    dp = Long.parseLong(DPTxt.getText()),
                    installmentAmount = Long.parseLong(installmentAmountTxt.getText()),
                    totalPrice, ppn, installmentPerMonth;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            ppn = totalPrice * 10 / 100;
            installmentPerMonth = (totalPrice + ppn) / installmentAmount;
            PPNTxt.setText("" + kursIndonesia.format(ppn));
            installmentMonthTxt.setText("" + kursIndonesia.format(installmentPerMonth));
        }
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if(orderNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama pemesan harus diisi");
            agreementCbx.setSelected(false);
        }else if(PPNTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tekan tombol proses terlebih dahulu");
            agreementCbx.setSelected(false);
        }else if(agreementCbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Pemesan menyetujui");
            agreementCbx.setSelected(true);
        }else{
            JOptionPane.showMessageDialog(null, "Pesanan belum disetujui");
            agreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementCbxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(agreementCbx.isSelected() == false){
            JOptionPane.showMessageDialog(null, 
                    "Klik centang checkbox untuk simpan data", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String typeHouse = null;
            if(tSilverRadioButton.isSelected()){
                typeHouse = "TYPE Silver";
            }else if(tGoldRadioButton.isSelected()){
                typeHouse= "TYPE Gold";
            }else{
                typeHouse = "TYPE Diamond";
            }
            try{
            String sql = "INSERT INTO rumah (name, area, tipe, luas, harga, jumlah_cicilan, cicilan_bulan) VALUES ('"
                        + orderNameTxt.getText() + "','"
                        + areaCbx.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + LargeLandTxt.getText() + "','"
                        + totalPriceTxt.getText() + "','"
                        + installmentAmountTxt.getText() + "','"
                        + installmentMonthTxt.getText() + "')";
            Connection conn = (Connection)ConnectionDB.connectDatabase();
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentFormNew.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
            DataForm dataForm = new DataForm();
            dataForm.setVisible(true);
            this.getDesktopPane().add(dataForm);
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void DPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPTxtActionPerformed
        
    }//GEN-LAST:event_DPTxtActionPerformed

    private void PPNTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPNTxtActionPerformed
       
    }//GEN-LAST:event_PPNTxtActionPerformed

    private void installmentMonthTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installmentMonthTxtActionPerformed
        
    }//GEN-LAST:event_installmentMonthTxtActionPerformed

    private void priceLandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceLandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceLandTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPTxt;
    private javax.swing.JTextField LargeLandTxt;
    private javax.swing.JTextField PPNTxt;
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JComboBox<String> areaCbx;
    private javax.swing.JTextField availableLandTxt;
    private javax.swing.JTextField buildingPriceTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField installmentAmountTxt;
    private javax.swing.JTextField installmentMonthTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton prosesButton;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton tDiamondRadioButton;
    private javax.swing.JRadioButton tGoldRadioButton;
    private javax.swing.JRadioButton tSilverRadioButton;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
